#easy_admin:
#    entities:
#        # List the entity class name you want to manage
#        - App\Entity\Product
#        - App\Entity\Category
#        - App\Entity\User

easy_admin:
    entities:
        - App\Entity\Product
        - App\Entity\Customer
        - App\Entity\Address
        - App\Entity\PaymentType
        - App\Entity\Order\Item
        - App\Entity\Order\Status
        - App\Entity\Order
